#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xE412B156EFF3855A (mandree@FreeBSD.org)
#
Name     : fetchmail
Version  : 7.0.0.alpha6
Release  : 1
URL      : https://versaweb.dl.sourceforge.net/project/fetchmail/branch_6.3/fetchmail-7.0.0-alpha6.tar.xz
Source0  : https://versaweb.dl.sourceforge.net/project/fetchmail/branch_6.3/fetchmail-7.0.0-alpha6.tar.xz
Source99 : https://versaweb.dl.sourceforge.net/project/fetchmail/branch_6.3/fetchmail-7.0.0-alpha6.tar.xz.asc
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: fetchmail-bin = %{version}-%{release}
Requires: fetchmail-license = %{version}-%{release}
Requires: fetchmail-locales = %{version}-%{release}
Requires: fetchmail-man = %{version}-%{release}
BuildRequires : bison
BuildRequires : flex
BuildRequires : openssl-dev
Patch1: 0001-Support-building-without-SSLv3.patch

%description
Fetchmail is a free, full-featured, robust, and well-documented remote
mail retrieval and forwarding utility intended to be used over
on-demand TCP/IP links (such as SLIP or PPP connections).  It
retrieves mail from remote mail servers and forwards it to your local
(client) machine's delivery system, so it can then be be read by
normal mail user agents such as mutt, elm, pine, (x)emacs/gnus, or mailx.
Comes with an interactive GUI configurator suitable for end-users.

%package bin
Summary: bin components for the fetchmail package.
Group: Binaries
Requires: fetchmail-license = %{version}-%{release}
Requires: fetchmail-man = %{version}-%{release}

%description bin
bin components for the fetchmail package.


%package license
Summary: license components for the fetchmail package.
Group: Default

%description license
license components for the fetchmail package.


%package locales
Summary: locales components for the fetchmail package.
Group: Default

%description locales
locales components for the fetchmail package.


%package man
Summary: man components for the fetchmail package.
Group: Default

%description man
man components for the fetchmail package.


%prep
%setup -q -n fetchmail-7.0.0-alpha6
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1549605935
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1549605935
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/fetchmail
cp COPYING %{buildroot}/usr/share/package-licenses/fetchmail/COPYING
%make_install
%find_lang fetchmail
## install_append content
rm -rf %{buildroot}/usr/lib/python*
rm -rf %{buildroot}/usr/bin/fetchmailconf
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/fetchmail

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/fetchmail/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/fetchmail.1
/usr/share/man/man1/fetchmailconf.1

%files locales -f fetchmail.lang
%defattr(-,root,root,-)

